from enum import Enum
class AuditActorType(str, Enum):
    CUSTOMER = "CUSTOMER"
    ADMIN = "ADMIN"
    DEVELOPER = "DEVELOPER"
    SYSTEM = "SYSTEM"
class AuditAction(str, Enum):
    AUTH_LOGIN = "AUTH_LOGIN"
    AUTH_SIGNUP = "AUTH_SIGNUP"
    REFUND_CREATED = "REFUND_CREATED"
    REFUND_APPROVED = "REFUND_APPROVED"
    REFUND_REJECTED = "REFUND_REJECTED"
    REFUND_PROCESSED = "REFUND_PROCESSED"
    CHAT_MESSAGE = "CHAT_MESSAGE"
    SECURITY = "SECURITY"
